# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 't7chickenplus' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    # Stripe
    pod 'Stripe', '~> 14.0.0'

  # Pods for t7chickenplus
  pod 'Firebase/Core'
  
  pod 'Google-Mobile-Ads-SDK'

  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 't7chickenplusTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 't7chickenplus-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for t7chickenplus-tvOS

  target 't7chickenplus-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
