# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

APP_ID = "org.t7chickenplus"
APP_PROFILE = "match Appstore org.t7chickenplus"
TEAM = "Nick DeJesus"


default_platform(:ios)
lane :ios_icon do
appicon(
  appicon_devices: [:iphone, :ios_marketing],
)
end

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "t7chickenplus.xcodeproj")
    build_app(workspace: "t7chickenplus.xcworkspace", scheme: "t7chickenplus")
    upload_to_app_store
  end
end


  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(
      type: "appstore",
      git_url: "https://github.com/ndejesus1227/t7-chicken-plus-codesign"
    ) # more information: https://codesigning.guide   
    gym(
      scheme: "t7chickenplus",
        export_options: {
          method: "app-store",
          export_xcargs: "-allowProvisioningUpdates",
          export_team_id: "Nick DeJesus",
          provisioningProfiles: { 
            "org.t7chickenplus" => "t7chickenplus",
            }
        }
      )
      pilot
    end

  lane :betaTest do
  build_app
  upload_to_testflight
  end
