# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

APP_ID = "org.t7chickenplus"
APP_PROFILE = "match Appstore org.t7chickenplus"
TEAM = "Nick DeJesus"

before_all do
  ensure_git_branch(branch: 'develop')
  ensure_git_status_clean
  git_pull
end


default_platform(:ios)
lane :ios_icon do
appicon(
  appicon_devices: [:iphone, :ios_marketing],
)
end

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "t7chickenplus.xcodeproj")
    build_app(workspace: "t7chickenplus.xcworkspace", scheme: "t7chickenplus")
    upload_to_app_store
  end
end

desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
  match(app_identifier: 't7chickenplus', type: 'development', readonly: true)
  match(app_identifier: 't7chickenplus', type: 'appstore', readonly: true)
end

desc 'Build the iOS application.'
private_lane :build do
  certificates
  increment_build_number
  gym(scheme: 't7chickenplus', project: './ios/t7chickenplus.xcodeproj')
end

desc 'Ship to Testflight.'
  lane :beta do
    build
    pilot
    commit_version_bump(message: 'Bump build', xcodeproj: './ios/t7chickenplus.xcodeproj')
    push_to_git_remote
  end