# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy a new alpha version to the Google Play Store"
  lane :alpha do
    gradle(
      task: "assemble",
      build_type: "Release"
    )
    supply(
      track: "alpha",
      apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    )
  end

  lane :show_version do
  version = get_version_name(app_project_dir: '**/app')
  UI.message(version)
  version_code = get_version_code(app_project_dir: '**/app')
  UI.message(version_code)
end

lane :bumpup do
  increment_version_name(app_project_dir: '**/app', bump_type: 'minor')
  increment_version_code(app_project_dir: '**/app')
end

lane :android_icon do
  android_appicon(
    appicon_path: 'app/res/drawable',
    appicon_icon_types: [:launcher],
    appicon_image_file: 'fastlane/metadata/app_icon.png'
  )
end

end
